apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.nginx.name }}:{{ .Values.image.nginx.tag }}"
          resources: 
            limits: 
              cpu: "1000m"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80
              name: http-metrics
          volumeMounts:
            - name: nginx-conf-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "15"]
        - name: nodejs
          image: "{{ .Values.image.app.name }}:{{ .Values.image.app.tag }}"
          resources: 
            limits: 
              cpu: "2000m"
          imagePullPolicy: IfNotPresent
          env:
            {{- range $key, $value := .Values.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
            - name: "PORT"
              value: "8080"
          ports:
            - containerPort: 8080
              name: app-metrics
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "15"]
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health-check
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health-check
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      volumes:
        - name: nginx-conf-volume
          configMap:
            name: backend-configmap
