apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ncc.instance }}-{{ .Values.ncc.installation }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: "TCP"
      name: web
  selector:
    {{- $nccLabels | nindent 4 }}
