apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  # TODO
  #annotations:
  #  external-dns.alpha.kubernetes.io/hostname: "frontend-svc.<NodeIP>.nip.io"
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: 'TCP'
      name: web
  selector:
    app: frontend-deployment
